version: 1.0.{build}
branches:
  only:
  - master
 
before_build:
- ps: nuget restore SmartHive\SmartHive.sln 
 
build:
  project: SmartHive\SmartHive.sln
  verbosity: minimal  

after_test: 
  - SmartHive\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"SmartHive\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single SmartHive\SmartHive.Web.Tests\bin\Debug\SmartHive.Web.Tests.dll SmartHive\SmartHive.Authentication.Tests\bin\Debug\SmartHive.Authentication.Tests.dll" -output:coverage.xml

  - SmartHive\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml